name: Trigger workflow

inputs:
  workflow:
    required: true

runs:
  using: composite
  permissions: write-all

  steps:
    - name: Trigger workflow
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: '${{ inputs.workflow }}.yml',
            ref: 'main'
          });
